# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: fryingduc
email: minhducbest2@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sharing my stories as undergrad competitive programming enthusiast
url: https://fryingduc.github.io
# twitter_username: jekyllrb
github_username:  fryingduc

# Build settings
# theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
# theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache

author:
  name   : "Giang Trung Minh Duc"
  avatar : "/images/avatar.png" # optional

# Social media accounts
social:
  github: fryingduc 
  facebook: Minh Duc

footer:
  links:
    - label: "Codeforces"
      icon: "fas fa-code"  # No official Codeforces icon; use something generic or custom
      url: "https://codeforces.com/profile/a65"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/fryingduc"
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://www.facebook.com/thanhduc.vu.94043/"

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
